//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipRemont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> Equipment_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Answer_id { get; set; }
        public Nullable<int> Status_id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
